// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bids.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createBid = `-- name: CreateBid :one
INSERT INTO bids (
    product_id,
    bidder_id,
    bid_amount_cents
) VALUES ($1, $2, $3)
RETURNING id, product_id, bidder_id, bid_amount_cents, created_at
`

type CreateBidParams struct {
	ProductID      uuid.UUID `json:"product_id"`
	BidderID       uuid.UUID `json:"bidder_id"`
	BidAmountCents int32     `json:"bid_amount_cents"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error) {
	row := q.db.QueryRow(ctx, createBid, arg.ProductID, arg.BidderID, arg.BidAmountCents)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BidderID,
		&i.BidAmountCents,
		&i.CreatedAt,
	)
	return i, err
}

const getBidsByProductId = `-- name: GetBidsByProductId :many
SELECT id, product_id, bidder_id, bid_amount_cents, created_at FROM bids
WHERE product_id = $1
ORDER BY bid_amount_cents DESC
LIMIT $2 OFFSET $3
`

type GetBidsByProductIdParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetBidsByProductId(ctx context.Context, arg GetBidsByProductIdParams) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidsByProductId, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BidderID,
			&i.BidAmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestBidByProductId = `-- name: GetHighestBidByProductId :one
SELECT id, product_id, bidder_id, bid_amount_cents, created_at FROM bids
WHERE product_id = $1
ORDER BY bid_amount_cents DESC
LIMIT 1
`

func (q *Queries) GetHighestBidByProductId(ctx context.Context, productID uuid.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, getHighestBidByProductId, productID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BidderID,
		&i.BidAmountCents,
		&i.CreatedAt,
	)
	return i, err
}
