// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID             uuid.UUID          `json:"id"`
	SellerID       uuid.UUID          `json:"seller_id"`
	ProductName    string             `json:"product_name"`
	Description    string             `json:"description"`
	BasePriceCents int32              `json:"base_price_cents"`
	AuctionEnd     time.Time          `json:"auction_end"`
	SoldAt         pgtype.Timestamptz `json:"sold_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	UserName     string             `json:"user_name"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Bio          string             `json:"bio"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
